functionsDirectory = "C:\\Users\\Parent\\Desktop\\Repository\\Tintbot.ai Final Build9.29\\netlify\\functions"
functionsDirectoryOrigin = "default"
headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[build]
publish = "C:\\Users\\Parent\\Desktop\\Repository\\Tintbot.ai Final Build9.29\\dist"
publishOrigin = "config"
commandOrigin = "config"
base = "C:\\Users\\Parent\\Desktop\\Repository\\Tintbot.ai Final Build9.29"
command = "npm run build"
functions = "C:\\Users\\Parent\\Desktop\\Repository\\Tintbot.ai Final Build9.29\\netlify\\functions"

[build.environment]
NODE_VERSION = "18"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[forms]]
name = "business-assessment-leads"

[[forms]]
name = "newsletter"

[[forms]]
name = "partnership-inquiry"

[functions]

[functions."*"]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "SAMEORIGIN"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
X-XSS-Protection = "1; mode=block"

[[headers]]
for = "*.js"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.css"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]