# Render Blueprint for Tintbot.ai
# Defines all services needed for the platform

services:
  # Main web application
  - type: web
    name: tintbot-ai-web
    env: node
    plan: starter
    buildCommand: npm run render-build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: tintbot-db
          property: connectionString
    domains:
      - tintbot.ai
      - www.tintbot.ai
      - "*.tintbot.ai"

  # Background worker for automation
  - type: worker
    name: tintbot-automation-worker
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node server/background-worker.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: tintbot-db
          property: connectionString

# Database
databases:
  - name: tintbot-db
    plan: starter
    databaseName: tintbot_production
    user: tintbot_admin
    ipAllowList: []

# Cron jobs for periodic tasks
jobs:
  - type: cron
    name: daily-cleanup
    plan: starter
    schedule: "0 2 * * *"  # Daily at 2 AM
    buildCommand: npm install
    startCommand: node server/cleanup.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tintbot-db
          property: connectionString
